#springfox.documentation.swagger.v2.host:

server:
  port: ${PORT:8080}

logging:
  level:
    com.jvilaverde.beers: debug

spring:
  datasource:
    initialization-mode: EMBEDDED
  cache:
    jcache:
      config: classpath:ehcache.xml
  artemis: # defaults for this docker image - vromero/activemq-artemis
    user: artemis
    password: simetraehcapa

sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082


